capitals = {
    "Argentina": "Buenos Aires",
    "Australia": "Canberra",
    "Austria": "Vienna",
    "Belgium": "Brussels",
    "Brazil": "Brasilia",
    "Canada": "Ottawa",
    "Chile": "Santiago",
    "China": "Beijing",
    "Colombia": "Bogota",
    "Croatia": "Zagreb",
    "Cuba": "Havana",
    "Czech Republic": "Prague",
    "Denmark": "Copenhagen",
    "Egypt": "Cairo",
    "Finland": "Helsinki",
    "France": "Paris",
    "Germany": "Berlin",
    "Greece": "Athens",
    "Hungary": "Budapest",
    "India": "New Delhi",
    "Indonesia": "Jakarta",
    "Iran": "Tehran",
    "Iraq": "Baghdad",
    "Ireland": "Dublin",
    "Israel": "Jerusalem",
    "Italy": "Rome",
    "Japan": "Tokyo",
    "Kenya": "Nairobi",
    "South Korea": "Seoul",
    "Lebanon": "Beirut",
    "Malaysia": "Kuala Lumpur",
    "Mexico": "Mexico City",
    "Netherlands": "Amsterdam",
    "New Zealand": "Wellington",
    "Nigeria": "Abuja",
    "Norway": "Oslo",
    "Pakistan": "Islamabad",
    "Philippines": "Manila",
    "Poland": "Warsaw",
    "Portugal": "Lisbon",
    "Romania": "Bucharest",
    "Russia": "Moscow",
    "Saudi Arabia": "Riyadh",
    "Singapore": "Singapore",
    "South Africa": "Pretoria",
    "Spain": "Madrid",
    "Sweden": "Stockholm",
    "Switzerland": "Bern",
    "Taiwan": "Taipei",
    "Thailand": "Bangkok",
    "Turkiye": "Ankara",
    "Ukraine": "Kyiv",
    "United Arab Emirates": "Abu Dhabi",
    "United Kingdom": "London",
    "United States of America": "Washington, D.C.",
    "Vietnam": "Hanoi"
}
